# Generated by Django 5.0.6 on 2024-07-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_file_date_alter_file_file_c_folder_file_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
    ]
